doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Shared/Infrastructure/Orm/Migrations'
    organize_migrations: BY_YEAR_AND_MONTH
    enable_profiler: false
