services:

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "54321:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: americor-loan-php
    volumes:
      - .:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: americor-loan-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/nginx/certs:ro
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data: